### ISSUE TITLE
大佬，这个GUI 的Mac Os 不太好使

### ISSUE THREAD

**Issue by Sologala** [monigo/srun#1]
Version 10.14.6 (18G95) Mojave
打开之后直接闪退

**Comment by Sologala** [comment]
还有 命令行的那个 Proj  里面的 release 的MAC 文件 ***.dms 文件咋用啊

**Comment by monigo** [comment]
> Version 10.14.6 (18G95) Mojave
> 打开之后直接闪退

不好意思，自动构建发布的程序没有签名所以闪退了，release已经修复
